services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: whatsapp_support_db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/lib/mssqlql/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqldata: